### ISSUE TITLE
Videobox support

### ISSUE THREAD

**Issue by cmirnow** [HitkoDev/Videobox-Joomla#1]
Hello. Tell please, how I can make YouTube Video gallery of  the 5 version Videobox ? The old format don't work:

`{videobox}5AG4pQPdZoE|,ATod-zbwMDE|,BqHTJfxBRww|,S9M3WaZSTBk|,eVoGpaCz8KE|,EPhTFLJiuYQ|,nHrMsr9spRk|,gt782I7ngUc{/videobox}`

**Comment by HitkoDev** [comment]
I've tested the code above on Joomla! 3.5 running Videobox 5.0.0 beta-2 and it seems to work fine. Please check that both `System - Videobox` and `Videobox - YouTube` plugins are enabled, since Joomla! doesn't auto-enable plugins upon installation. If that doesn't solve the problem, open the `System - Videobox` plugin and click `Save`, in case the plugin settings haven't been properly saved upon installation.

**Comment by cmirnow** [comment]
Many thanks!
"open the System - Videobox plugin and click Save" - It works.
Otherwise, we get "Invalid image geometry" on the page.
Another question, if I may.  In FF scrolling of slider does not work smoothly - http://melodicpictures.ru/video. Your opinion?

```
[aleksej@localhost ~]$ LC_ALL=C dnf info firefox
Last metadata expiration check: 25 days, 0:49:24 ago on Sun Mar 13 18:01:56 2016.
Installed Packages
Name        : firefox
Arch        : x86_64
Epoch       : 0
Version     : 45.0.1
Release     : 2.fc23
Size        : 128 M
Repo        : @System
From repo   : updates
Summary     : Mozilla Firefox Web browser
```

**Comment by HitkoDev** [comment]
Web animations standard isn't supported in all browsers yet, which is why these browsers use a JavaScript polyfill that doesn't work as smooth. However, browsers that do support Web animations have a native implementation for it, which is much more optimised and utilises hardware acceleration, which is why I prefer it over jQuery or older JavaScript animations.

**Comment by cmirnow** [comment]
I don't can change color of arrows in the slider: 
plugin Videobox -> tab Main -> Player color. 
I was made it in the css-file... this does not work?

**Comment by HitkoDev** [comment]
I've removed your question and opened a new [issue](2). In future please don't post unrelated problems under the same issue.
