### ISSUE TITLE
modification to video gallery

### ISSUE THREAD

**Issue by ericcuthbert** [HitkoDev/Videobox-Joomla#11]
Hi,
I am building a new Joomla web site Can you give me a price to modify your video gallery I would like visitors to my web page to view the gallery full page  layout I would like a modular with  link where visitors can upload their video direct to my YouTube Gallery without using any passwords or user names so can these be auto filled into YouTube if needed this is to make it very easy for visitors to upload their video
Once it is on the gallery I would like the video to appear on my Joomla web site in your gallery
I would also like beside each video a vote button so visitors can vote for the best video every month I would need some methods to count the votes so the video with most votes win
Regards Eric

**Comment by HitkoDev** [comment]
Hello,
to achieve this you're going to need a custom Joomla! component which integrates with the Videobox plugin. It is possible to upload videos in two ways: 
- using an access token (unsafe as it allows anyone to access the account where videos are stored)
- through Google account (users have to log in using Google in order to upload videos)

Please contact me at development@hitko.si for more details
