### ISSUE TITLE
5.0 not left aligned nor has play button

### ISSUE THREAD

**Issue by cybertrax2** [HitkoDev/Videobox-Joomla#14]
Upgraded from old version to 5.0 simply by uninstalling old version then installing new version; previously tried to install over the top of old version and website crashed!  Videos play, but no play button shows now, videos do not autoplay after opening in lightbox and more importantly the thumbnails are no longer left aligned.  Have tried clearing cache, and according to code should be left aligning.  Can you please have a look?  Website in question:  http://kingfisherdecor.com/index.php/mural-videos-gallery/chediston.

**Comment by HitkoDev** [comment]
Have you followed the [Upgrading to Videobox 5](https://hitko.eu/videobox/getting-started/#htk-upgrading-to-videobox-5) guide? Videobox 5 uses a different configuration syntax, therefore you'll have to update your config as well in order to get it left-aligned again. From what you're saying it sounds like you should use the following code:

`{videobox? &class=`vb_play_button` &style=`float: left; margin-right: 10px;` &display=`box`}/articlevideos/Chediston.mp4{/videobox}`

I've tested it on a clean Joomla! 3.6 install and I got a left-aligned thumbnail with a play button. As for the autoplay issue, it looks like the player library wasn't properly listed in the manifest file, it should be fixed in [5.0.1](https://github.com/HitkoDev/Videobox-Joomla/releases/tag/v5.0.1).
