### ISSUE TITLE
Video box plugin crashes my site

### ISSUE THREAD

**Issue by snakegun** [HitkoDev/Videobox-Joomla#17]
I installed the plugin and enabled System - Videobox, then I can't even visit my site at all.  Not sure if an known issue?

http://namecheap.acpc.org.nz/index.php/zh-cn/sermon-zh/sermon-zh-all/16-20160904

Regards
Coby

**Comment by HitkoDev** [comment]
You're using an old version of Joomla! As it says on JED, Videobox only works with Joomla! 3.6 or later (http://extensions.joomla.org/extensions/extension/multimedia/multimedia-players/videobox):

> Videobox is a Joomla! 3.6 extension ...

Update your Joomla! in order to fix this issue. Also follow the [Getting started guide](https://hitko.eu/videobox/getting-started/) and make sure your server meets other requirements.
