### ISSUE TITLE
Videobox - Joomla - php error divide by zero

### ISSUE THREAD

**Issue by NMF101A** [HitkoDev/Videobox-Joomla#6]
I have installed the latest version of Videobox for Joomla 3.5 and when attempting to use it I receive the following error message:

Warning: Division by zero in /home/yenofie/public_html/plugins/system/videobox/videobox.php on line 291

Please advise on how to fix this problem.

**Comment by tumbleweed95** [comment]
Hello, 
I'm not an expert, but I think that I had the same error.
The solution is **to edit** the plugin videobox system, you set plugin Status to Enabled and **save it.**
When you set the plugin with the list and without edit it, it doesn't work .
Regards

**Comment by HitkoDev** [comment]
There's a rather annoying bug with Joomla! - the subforms (each property set is a subform) don't have a default value set on install, so you have to edit and save the plugin manually in order for it to properly load the config. I've opened an issue here: https://github.com/joomla/joomla-cms/issues/11318, hopefully it gets fixed, because I haven't managed to find a workaround yet.

**Comment by EdwardsDS17** [comment]
Totally agree, I have just updated Videobox to the latest version and my thumbnails disappeared, even though they were all showing as enabled. I disabled each one from the list and then opened each plugin and enabled it.  Everything now working as it should.

**Comment by HitkoDev** [comment]
Since there hasn't been much interest among Joomla! core developers, I've been forced to write a (rather dirty) [workaround](https://github.com/HitkoDev/Videobox-Joomla/blob/master/src/plugins/videobox/scripts.php#L39). It's included in the latest release candidate, and it should solve this problem when installing / updating Videobox. 

If no similar problems occur with rc5 I'm going to close this issue in a few days.
